### ISSUE TITLE
Running sif.py throws ModuleNotFound errors

### ISSUE THREAD

**Issue by Tuckertcs** [BlueManCZ/SIF#1]
Here's the following errors. This is after a fresh install.
```
tucker@tucker-desktop:~/SIF$ ./sif.py --icons
Traceback (most recent call last):
  File "./sif.py", line 13, in <module>
    import vdf
ModuleNotFoundError: No module named 'vdf'
```

```
tucker@tucker-desktop:~/SIF$ ./sif.py --pretend
Traceback (most recent call last):
  File "./sif.py", line 13, in <module>
    import vdf
ModuleNotFoundError: No module named 'vdf'
```

```
tucker@tucker-desktop:~/SIF$ ./sif.py
Traceback (most recent call last):
  File "./sif.py", line 13, in <module>
    import vdf
ModuleNotFoundError: No module named 'vdf'
```

**Comment by BlueManCZ** [comment]
Hello, thank you for your feedback. I should put dependencies into a readme. You need to install vdf module into python. https://pypi.org/project/vdf/

If you have `pip3`, just run `sudo pip3 install vdf`
