### ISSUE TITLE
Can't use Browse

### ISSUE THREAD

**Issue by Fancy2209** [BlueManCZ/SIF#22]
When I try to use the browse function of SIF it throws me this:
```                                                             ✔ 
Gtk-Message: 12:41:34.361: Failed to load module "unity-gtk-module"
Working with Papirus icon theme.

These Steam games have icon in Papirus icon theme:
(Fetching names from https://steamdb.info/. This may take a while.)

Traceback (most recent call last):
  File "/home/paulo/Papirus/SIF/./sif.py", line 298, in <module>
    name = get_game_name(fetch_json(game))
  File "/home/paulo/Papirus/SIF/./sif.py", line 140, in get_game_name
    data = loads(json_string)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Fancy2209** [comment]
I was testing Unity when I copied that but it also fails on Gnome

**Comment by BlueManCZ** [comment]
Hello, thank you for letting me know! It should be fixed now. But please keep in mind that `--browse` is an experimental option and is using limited free Steam API. So you will probably get only a few first tens of games, but not all of them.
